version: '3.3'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: skynotes
      POSTGRES_PASSWORD: skynotes
      POSTGRES_DB: skynotes
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "skynotes"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      dockerfile: Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./skynotes:/code

  migrations:
    build:
      dockerfile: Dockerfile
    restart: no
    command: python manage.py migrate --noinput && python manage.py createcachetable
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./skynotes:/code

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=skynotes
      - RABBITMQ_DEFAULT_PASS=skynotes
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build:
      dockerfile: Dockerfile
    restart: always
    command: celery -A skynotes worker -l info
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
      app:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./skynotes:/code

  cache:
    image: redis:latest
    ports:
      - 6379:6379
    command: >
          --requirepass skynotes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  thumbnailer:
    build:
      dockerfile: thumbnailer.Dockerfile
      context: .  # use the same context as the app service (in future)
    restart: always
    ports:
      - 50051:50051