version: '3.3'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: skynotes
      POSTGRES_PASSWORD: skynotes
      POSTGRES_DB: skynotes
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "skynotes"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      dockerfile: Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./skynotes:/code
    
  migrations:
    build:
      dockerfile: Dockerfile
    restart: no
    command: python manage.py migrate --noinput
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
      app:
        condition: service_started
    volumes:
      - .:/app
