# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import thumbnailer.thumbnailer_pb2 as thumbnailer__pb2


class ThumbnailServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateThumbnail = channel.unary_unary(
            "/thumbnailer.ThumbnailService/GenerateThumbnail",
            request_serializer=thumbnailer__pb2.ThumbnailRequest.SerializeToString,
            response_deserializer=thumbnailer__pb2.ThumbnailResponse.FromString,
        )


class ThumbnailServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateThumbnail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ThumbnailServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GenerateThumbnail": grpc.unary_unary_rpc_method_handler(
            servicer.GenerateThumbnail,
            request_deserializer=thumbnailer__pb2.ThumbnailRequest.FromString,
            response_serializer=thumbnailer__pb2.ThumbnailResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "thumbnailer.ThumbnailService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ThumbnailService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateThumbnail(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/thumbnailer.ThumbnailService/GenerateThumbnail",
            thumbnailer__pb2.ThumbnailRequest.SerializeToString,
            thumbnailer__pb2.ThumbnailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
