# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thumbnailer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11thumbnailer.proto\x12\x0bthumbnailer"#\n\x10ThumbnailRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c"&\n\x11ThumbnailResponse\x12\x11\n\tthumbnail\x18\x01 \x01(\x0c\x32\x66\n\x10ThumbnailService\x12R\n\x11GenerateThumbnail\x12\x1d.thumbnailer.ThumbnailRequest\x1a\x1e.thumbnailer.ThumbnailResponseB\x08Z\x06./grpcb\x06proto3'  # noqa
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "thumbnailer_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:  # noqa
    _globals["DESCRIPTOR"]._options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\006./grpc"
    _globals["_THUMBNAILREQUEST"]._serialized_start = 34
    _globals["_THUMBNAILREQUEST"]._serialized_end = 69
    _globals["_THUMBNAILRESPONSE"]._serialized_start = 71
    _globals["_THUMBNAILRESPONSE"]._serialized_end = 109
    _globals["_THUMBNAILSERVICE"]._serialized_start = 111
    _globals["_THUMBNAILSERVICE"]._serialized_end = 213
# @@protoc_insertion_point(module_scope)
