# Generated by Django 5.0 on 2024-02-12 15:42

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=16, null=True
                        ),
                        blank=True,
                        null=True,
                        size=6,
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                ("size", models.PositiveBigIntegerField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "shared_until",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="storage.file"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip", models.GenericIPAddressField()),
                ("user_agent", models.CharField(blank=True, max_length=512, null=True)),
                ("referer", models.URLField(blank=True, null=True)),
                (
                    "file_share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storage.fileshare",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("default", "default"),
                            ("music", "music"),
                            ("video", "video"),
                            ("photo", "photo"),
                            ("document", "document"),
                            ("archive", "archive"),
                        ],
                        default="default",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="file",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="storage.group",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileshare",
            constraint=models.CheckConstraint(
                check=models.Q(("shared_until__gt", models.F("created_at"))),
                name="storage_fileshare_shared_until_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileanalytics",
            constraint=models.CheckConstraint(
                check=models.Q(("ip__isnull", False)),
                name="storage_fileanalytics_ip_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileanalytics",
            constraint=models.CheckConstraint(
                check=models.Q(("user_agent__isnull", False)),
                name="storage_fileanalytics_user_agent_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "icon__in",
                        ["default", "music", "video", "photo", "document", "archive"],
                    )
                ),
                name="storage_group_icon_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                check=models.Q(("size__gt", 0)), name="storage_file_size_valid"
            ),
        ),
    ]
