# Generated by Django 5.0 on 2024-02-12 01:40

import django.db.models.deletion
import storage.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=storage.utils.generate_id,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip", models.GenericIPAddressField()),
                ("user_agent", models.CharField(blank=True, max_length=512, null=True)),
                ("referer", models.URLField(blank=True, null=True)),
                (
                    "file_share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storage.fileshare",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="fileanalytics",
            constraint=models.CheckConstraint(
                check=models.Q(("ip__isnull", False)),
                name="storage_fileanalytics_ip_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileanalytics",
            constraint=models.CheckConstraint(
                check=models.Q(("user_agent__isnull", False)),
                name="storage_fileanalytics_user_agent_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileanalytics",
            constraint=models.CheckConstraint(
                check=models.Q(("referer__isnull", False)),
                name="storage_fileanalytics_referer_valid",
            ),
        ),
    ]
