# Generated by Django 5.0 on 2024-02-12 02:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0002_fileanalytics_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fileanalytics",
            name="storage_fileanalytics_referer_valid",
        ),
    ]
