# Generated by Django 5.0 on 2024-01-10 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0002_file_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="storage.group",
            ),
        ),
    ]
