# Generated by Django 5.0 on 2024-01-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0004_alter_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
