# Generated by Django 5.0 on 2024-01-11 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0005_alter_group_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="group",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "icon__in",
                        ["default", "music", "video", "photo", "document", "archive"],
                    )
                ),
                name="storage_group_icon_valid",
            ),
        ),
    ]
