# Generated by Django 5.0 on 2024-02-03 14:52

import django.db.models.deletion
import storage.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0007_file_size"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=storage.utils.generate_id,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("shared_until", models.DateTimeField(blank=True, null=True)),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "token",
                    models.UUIDField(
                        default=storage.utils.generate_id, editable=False, unique=True
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.CheckConstraint(
                check=models.Q(("size__gt", 0)), name="storage_file_size_valid"
            ),
        ),
        migrations.AddField(
            model_name="fileshare",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="storage.file"
            ),
        ),
        migrations.AddConstraint(
            model_name="fileshare",
            constraint=models.CheckConstraint(
                check=models.Q(("shared_until__gt", models.F("created_at"))),
                name="storage_fileshare_shared_until_valid",
            ),
        ),
    ]
