# Generated by Django 5.0 on 2024-02-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0008_fileshare_file_storage_file_size_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileshare",
            name="shared_until",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
