# Generated by Django 5.0 on 2024-01-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="storage_limit",
            field=models.BigIntegerField(default=5368709120),
        ),
    ]
