# Generated by Django 5.0 on 2024-02-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0002_user_storage_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="storage_limit",
            field=models.BigIntegerField(default=1368709120),
        ),
    ]
