# Generated by Django 4.2.7 on 2024-01-06 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("notes", "0004_alter_file_options"),
        ("authorization", "0003_customuser_groups_customuser_user_permissions"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomUser",
            new_name="User",
        ),
    ]
