# Generated by Django 5.0 on 2023-12-29 02:17

import django.contrib.postgres.fields
import django.db.models.deletion
import notes.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=notes.utils.generate_id,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("default", "default"),
                            ("music", "music"),
                            ("video", "video"),
                            ("photo", "photo"),
                            ("document", "document"),
                            ("archive", "archive"),
                        ],
                        default="default",
                    ),
                ),
                ("description", models.CharField(max_length=512)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=notes.utils.generate_id,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16),
                        blank=True,
                        null=True,
                        size=6,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notes.group",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
