# Generated by Django 5.0 on 2023-12-31 00:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"ordering": ["name"]},
        ),
    ]
