# Generated by Django 5.0 on 2024-01-05 10:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=16, null=True),
                blank=True,
                null=True,
                size=6,
            ),
        ),
    ]
