name: API Pre-deploy

on:
  push:
    paths:
        - 'skynotes/**'
        - '.github/workflows/**'
    branches:
      - master
      - develop
  pull_request:
    paths:
        - 'skynotes/**'
        - '.github/workflows/**'
    branches:
      - master
      - develop

jobs:
    lint:
        name: Lint code
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            
            - name: Setup Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: 3.11
            
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            - name: Lint with flake8
              run: |
                    python -m flake8 skynotes
            
            - name: Check black
              run: |
                    python -m black skynotes --check
            
            - name: Check isort
              run: |
                    python -m isort skynotes --check-only